# Generated by Django 4.2.2 on 2024-09-08 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="почта"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="имя")),
                ("surname", models.CharField(max_length=150, verbose_name="фамилия")),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="коментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ("name", "surname"),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_message",
                    models.CharField(max_length=100, verbose_name="тема сообщения"),
                ),
                (
                    "title_message",
                    models.CharField(max_length=100, verbose_name="заголовок"),
                ),
                ("body_message", models.TextField(verbose_name="сообщение")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("title_message", "topic_message"),
            },
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="заголовок"
                    ),
                ),
                (
                    "datetime_start",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        verbose_name="дата и время отправки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "раз в день"),
                            ("weekly", "раз в неделю"),
                            ("monthly", "раз в месяц"),
                        ],
                        max_length=20,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("launched", "отправлена"),
                            ("cancelled", "отменена"),
                            ("completed", "завершена"),
                            ("deleted", "удалена"),
                        ],
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="dispatch",
                        to="mailing.client",
                        verbose_name="клиенты",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch",
                        to="mailing.message",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("title", "datetime_start", "status"),
            },
        ),
        migrations.CreateModel(
            name="Attempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        verbose_name="дата и время последней отправки"
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="успешно")),
                (
                    "mail_response",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ответ почтового сервиса",
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing.dispatch",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
                "ordering": ("datetime", "status", "dispatch"),
            },
        ),
    ]
