# Generated by Django 4.2.2 on 2024-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("раз в день", "раз в день"),
                    ("раз в неделю", "раз в неделю"),
                    ("раз в месяц", "раз в месяц"),
                ],
                max_length=20,
                verbose_name="периодичность",
            ),
        ),
    ]
