# Generated by Django 4.2.2 on 2024-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_dispatch_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatch",
            options={
                "ordering": ("title", "first_sent_date_time", "status"),
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="dispatch",
            name="datetime_start",
        ),
        migrations.AddField(
            model_name="dispatch",
            name="first_sent_date_time",
            field=models.DateTimeField(
                default=None, verbose_name="дата и время первой отправки"
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="last_sent_date_time",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="дата и время последней отправки",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="next_sent_date_time",
            field=models.DateTimeField(
                default=None, verbose_name="дата и время следующей отправки"
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("создана", "создана"),
                    ("запущена", "отправлена"),
                    ("отменена", "отменена"),
                    ("завершена", "завершена"),
                ],
                max_length=20,
                verbose_name="статус",
            ),
        ),
    ]
