# Generated by Django 4.2.2 on 2024-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_dispatch_next_sent_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="first_sent_date_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата и время первой отправки"
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="next_sent_date_time",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="дата и время следующей отправки",
            ),
        ),
    ]
