# Generated by Django 4.2.2 on 2024-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_dispatch_first_sent_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatch",
            name="next_sent_date_time",
        ),
        migrations.AddField(
            model_name="dispatch",
            name="next_send_date_time",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="дата и время следующей отправки",
            ),
        ),
    ]
