# Generated by Django 4.2.2 on 2024-09-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_remove_dispatch_next_sent_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("создана", "создана"),
                    ("запущена", "запущена"),
                    ("отменена", "отменена"),
                    ("завершена", "завершена"),
                ],
                default="создана",
                max_length=20,
                verbose_name="статус",
            ),
        ),
    ]
