# Generated by Django 4.2.2 on 2024-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_dispatch_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="first_sent_date_time",
            field=models.DateTimeField(verbose_name="дата и время первой отправки"),
        ),
    ]
