# Generated by Django 4.2.2 on 2024-09-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_alter_dispatch_last_sent_date_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dispatch",
            old_name="next_send_date_time",
            new_name="next_sent_date_time",
        ),
    ]
