# Generated by Django 4.2.2 on 2024-09-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0013_dispatch_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatch",
            options={
                "ordering": ("title", "first_sent_date_time", "status"),
                "permissions": [("can_edit_status", "Can edit status")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
