# Generated by Django 4.2.2 on 2024-09-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0016_alter_dispatch_options_dispatch_is_activ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="is_activ",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
