# Generated by Django 4.2.2 on 2024-09-12 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog/blog/picture",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликованно"),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Просмотры"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ("title", "content"),
                "permissions": [("can_edit_published", "Can edit is_published")],
            },
        ),
    ]
